/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sjay2
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
public class Remove_book extends javax.swing.JFrame {

    /**
     * Creates new form Remove_book
     */
    public Remove_book() {
        initComponents();
        setDefaultCloseOperation(Remove_book.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bookIdOrNameField = new javax.swing.JTextField();
        deleteTheBook = new javax.swing.JButton();
        cancelTheDelelteOper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER THE BOOK ID OR BOOK NAME TO DELETE");

        bookIdOrNameField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookIdOrNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bookIdOrNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookIdOrNameFieldActionPerformed(evt);
            }
        });

        deleteTheBook.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteTheBook.setText("DELETE");
        deleteTheBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTheBookActionPerformed(evt);
            }
        });

        cancelTheDelelteOper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelTheDelelteOper.setText("CANCEL");
        cancelTheDelelteOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTheDelelteOperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                            .addComponent(bookIdOrNameField))
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(deleteTheBook, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelTheDelelteOper, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(bookIdOrNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTheBook, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelTheDelelteOper, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookIdOrNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookIdOrNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookIdOrNameFieldActionPerformed

    private void deleteTheBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTheBookActionPerformed
        // TODO add your handling code here:
        String url= "jdbc:mysql://localhost/library";
        String mysqluser="root";
        String mysqlpwd = "Mysql@jay";
        String input = bookIdOrNameField.getText();
        String query ="delete from books where book_id='"+input+"' or name='"+input+"';";
        try{
            Connection conn = DriverManager.getConnection(url,mysqluser,mysqlpwd);
            Statement stm = conn.createStatement();
           int rows = stm.executeUpdate(query);
           if(rows>0){
                JOptionPane.showMessageDialog(this,"Book removed from library successfully");
           }else{
                JOptionPane.showMessageDialog(this,"No such is book available");
            }
           
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_deleteTheBookActionPerformed

    private void cancelTheDelelteOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTheDelelteOperActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelTheDelelteOperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIdOrNameField;
    private javax.swing.JButton cancelTheDelelteOper;
    private javax.swing.JButton deleteTheBook;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
