/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sjay2
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;
public class Remove_staff extends javax.swing.JFrame {

    /**
     * Creates new form Remove_staff
     */
    public Remove_staff() {
        initComponents();
        setDefaultCloseOperation(Remove_book.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputStaffIdOrNameField = new javax.swing.JTextField();
        deleteTheStaffMem = new javax.swing.JButton();
        cancelTheDeleteOper = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENTER THE STAFF ID OR NAME TO DELETE");

        inputStaffIdOrNameField.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputStaffIdOrNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        deleteTheStaffMem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        deleteTheStaffMem.setText("DELETE");
        deleteTheStaffMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTheStaffMemActionPerformed(evt);
            }
        });

        cancelTheDeleteOper.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelTheDeleteOper.setText("CANCEL");
        cancelTheDeleteOper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelTheDeleteOperActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputStaffIdOrNameField)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(deleteTheStaffMem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(cancelTheDeleteOper, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(inputStaffIdOrNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteTheStaffMem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelTheDeleteOper, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteTheStaffMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTheStaffMemActionPerformed
        // TODO add your handling code here:
                String url= "jdbc:mysql://localhost/library";
        String mysqluser="root";
        String mysqlpwd = "Mysql@jay";
        String input = inputStaffIdOrNameField.getText();
        String query ="delete from staff where staff_id='"+input+"' or name='"+input+"';";
        try{
            Connection conn = DriverManager.getConnection(url,mysqluser,mysqlpwd);
            Statement stm = conn.createStatement();
           int rows = stm.executeUpdate(query);
           if(rows>0){
                JOptionPane.showMessageDialog(this,"Staff member removed from library successfully");
           }else{
                JOptionPane.showMessageDialog(this,"No such is staff member present");
            }
           
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_deleteTheStaffMemActionPerformed

    private void cancelTheDeleteOperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelTheDeleteOperActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelTheDeleteOperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelTheDeleteOper;
    private javax.swing.JButton deleteTheStaffMem;
    private javax.swing.JTextField inputStaffIdOrNameField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
